
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EpisodeWatch` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EpisodeWatch
 * 
 */
export type EpisodeWatchModel = runtime.Types.Result.DefaultSelection<Prisma.$EpisodeWatchPayload>

export type AggregateEpisodeWatch = {
  _count: EpisodeWatchCountAggregateOutputType | null
  _avg: EpisodeWatchAvgAggregateOutputType | null
  _sum: EpisodeWatchSumAggregateOutputType | null
  _min: EpisodeWatchMinAggregateOutputType | null
  _max: EpisodeWatchMaxAggregateOutputType | null
}

export type EpisodeWatchAvgAggregateOutputType = {
  tmdbId: number | null
  seasonNumber: number | null
  episodeNumber: number | null
}

export type EpisodeWatchSumAggregateOutputType = {
  tmdbId: number | null
  seasonNumber: number | null
  episodeNumber: number | null
}

export type EpisodeWatchMinAggregateOutputType = {
  id: string | null
  username: string | null
  tmdbId: number | null
  seasonNumber: number | null
  episodeNumber: number | null
  watchedAt: Date | null
}

export type EpisodeWatchMaxAggregateOutputType = {
  id: string | null
  username: string | null
  tmdbId: number | null
  seasonNumber: number | null
  episodeNumber: number | null
  watchedAt: Date | null
}

export type EpisodeWatchCountAggregateOutputType = {
  id: number
  username: number
  tmdbId: number
  seasonNumber: number
  episodeNumber: number
  watchedAt: number
  _all: number
}


export type EpisodeWatchAvgAggregateInputType = {
  tmdbId?: true
  seasonNumber?: true
  episodeNumber?: true
}

export type EpisodeWatchSumAggregateInputType = {
  tmdbId?: true
  seasonNumber?: true
  episodeNumber?: true
}

export type EpisodeWatchMinAggregateInputType = {
  id?: true
  username?: true
  tmdbId?: true
  seasonNumber?: true
  episodeNumber?: true
  watchedAt?: true
}

export type EpisodeWatchMaxAggregateInputType = {
  id?: true
  username?: true
  tmdbId?: true
  seasonNumber?: true
  episodeNumber?: true
  watchedAt?: true
}

export type EpisodeWatchCountAggregateInputType = {
  id?: true
  username?: true
  tmdbId?: true
  seasonNumber?: true
  episodeNumber?: true
  watchedAt?: true
  _all?: true
}

export type EpisodeWatchAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EpisodeWatch to aggregate.
   */
  where?: Prisma.EpisodeWatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EpisodeWatches to fetch.
   */
  orderBy?: Prisma.EpisodeWatchOrderByWithRelationInput | Prisma.EpisodeWatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EpisodeWatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EpisodeWatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EpisodeWatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EpisodeWatches
  **/
  _count?: true | EpisodeWatchCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EpisodeWatchAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EpisodeWatchSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EpisodeWatchMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EpisodeWatchMaxAggregateInputType
}

export type GetEpisodeWatchAggregateType<T extends EpisodeWatchAggregateArgs> = {
      [P in keyof T & keyof AggregateEpisodeWatch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEpisodeWatch[P]>
    : Prisma.GetScalarType<T[P], AggregateEpisodeWatch[P]>
}




export type EpisodeWatchGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EpisodeWatchWhereInput
  orderBy?: Prisma.EpisodeWatchOrderByWithAggregationInput | Prisma.EpisodeWatchOrderByWithAggregationInput[]
  by: Prisma.EpisodeWatchScalarFieldEnum[] | Prisma.EpisodeWatchScalarFieldEnum
  having?: Prisma.EpisodeWatchScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EpisodeWatchCountAggregateInputType | true
  _avg?: EpisodeWatchAvgAggregateInputType
  _sum?: EpisodeWatchSumAggregateInputType
  _min?: EpisodeWatchMinAggregateInputType
  _max?: EpisodeWatchMaxAggregateInputType
}

export type EpisodeWatchGroupByOutputType = {
  id: string
  username: string
  tmdbId: number
  seasonNumber: number
  episodeNumber: number
  watchedAt: Date
  _count: EpisodeWatchCountAggregateOutputType | null
  _avg: EpisodeWatchAvgAggregateOutputType | null
  _sum: EpisodeWatchSumAggregateOutputType | null
  _min: EpisodeWatchMinAggregateOutputType | null
  _max: EpisodeWatchMaxAggregateOutputType | null
}

export type GetEpisodeWatchGroupByPayload<T extends EpisodeWatchGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EpisodeWatchGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EpisodeWatchGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EpisodeWatchGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EpisodeWatchGroupByOutputType[P]>
      }
    >
  >



export type EpisodeWatchWhereInput = {
  AND?: Prisma.EpisodeWatchWhereInput | Prisma.EpisodeWatchWhereInput[]
  OR?: Prisma.EpisodeWatchWhereInput[]
  NOT?: Prisma.EpisodeWatchWhereInput | Prisma.EpisodeWatchWhereInput[]
  id?: Prisma.StringFilter<"EpisodeWatch"> | string
  username?: Prisma.StringFilter<"EpisodeWatch"> | string
  tmdbId?: Prisma.IntFilter<"EpisodeWatch"> | number
  seasonNumber?: Prisma.IntFilter<"EpisodeWatch"> | number
  episodeNumber?: Prisma.IntFilter<"EpisodeWatch"> | number
  watchedAt?: Prisma.DateTimeFilter<"EpisodeWatch"> | Date | string
}

export type EpisodeWatchOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  watchedAt?: Prisma.SortOrder
}

export type EpisodeWatchWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  username_tmdbId_seasonNumber_episodeNumber?: Prisma.EpisodeWatchUsernameTmdbIdSeasonNumberEpisodeNumberCompoundUniqueInput
  AND?: Prisma.EpisodeWatchWhereInput | Prisma.EpisodeWatchWhereInput[]
  OR?: Prisma.EpisodeWatchWhereInput[]
  NOT?: Prisma.EpisodeWatchWhereInput | Prisma.EpisodeWatchWhereInput[]
  username?: Prisma.StringFilter<"EpisodeWatch"> | string
  tmdbId?: Prisma.IntFilter<"EpisodeWatch"> | number
  seasonNumber?: Prisma.IntFilter<"EpisodeWatch"> | number
  episodeNumber?: Prisma.IntFilter<"EpisodeWatch"> | number
  watchedAt?: Prisma.DateTimeFilter<"EpisodeWatch"> | Date | string
}, "id" | "username_tmdbId_seasonNumber_episodeNumber">

export type EpisodeWatchOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  watchedAt?: Prisma.SortOrder
  _count?: Prisma.EpisodeWatchCountOrderByAggregateInput
  _avg?: Prisma.EpisodeWatchAvgOrderByAggregateInput
  _max?: Prisma.EpisodeWatchMaxOrderByAggregateInput
  _min?: Prisma.EpisodeWatchMinOrderByAggregateInput
  _sum?: Prisma.EpisodeWatchSumOrderByAggregateInput
}

export type EpisodeWatchScalarWhereWithAggregatesInput = {
  AND?: Prisma.EpisodeWatchScalarWhereWithAggregatesInput | Prisma.EpisodeWatchScalarWhereWithAggregatesInput[]
  OR?: Prisma.EpisodeWatchScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EpisodeWatchScalarWhereWithAggregatesInput | Prisma.EpisodeWatchScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EpisodeWatch"> | string
  username?: Prisma.StringWithAggregatesFilter<"EpisodeWatch"> | string
  tmdbId?: Prisma.IntWithAggregatesFilter<"EpisodeWatch"> | number
  seasonNumber?: Prisma.IntWithAggregatesFilter<"EpisodeWatch"> | number
  episodeNumber?: Prisma.IntWithAggregatesFilter<"EpisodeWatch"> | number
  watchedAt?: Prisma.DateTimeWithAggregatesFilter<"EpisodeWatch"> | Date | string
}

export type EpisodeWatchCreateInput = {
  id?: string
  username: string
  tmdbId: number
  seasonNumber: number
  episodeNumber: number
  watchedAt?: Date | string
}

export type EpisodeWatchUncheckedCreateInput = {
  id?: string
  username: string
  tmdbId: number
  seasonNumber: number
  episodeNumber: number
  watchedAt?: Date | string
}

export type EpisodeWatchUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  watchedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EpisodeWatchUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  watchedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EpisodeWatchCreateManyInput = {
  id?: string
  username: string
  tmdbId: number
  seasonNumber: number
  episodeNumber: number
  watchedAt?: Date | string
}

export type EpisodeWatchUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  watchedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EpisodeWatchUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  watchedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EpisodeWatchUsernameTmdbIdSeasonNumberEpisodeNumberCompoundUniqueInput = {
  username: string
  tmdbId: number
  seasonNumber: number
  episodeNumber: number
}

export type EpisodeWatchCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  watchedAt?: Prisma.SortOrder
}

export type EpisodeWatchAvgOrderByAggregateInput = {
  tmdbId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
}

export type EpisodeWatchMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  watchedAt?: Prisma.SortOrder
}

export type EpisodeWatchMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  watchedAt?: Prisma.SortOrder
}

export type EpisodeWatchSumOrderByAggregateInput = {
  tmdbId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
}



export type EpisodeWatchSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  tmdbId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  watchedAt?: boolean
}, ExtArgs["result"]["episodeWatch"]>

export type EpisodeWatchSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  tmdbId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  watchedAt?: boolean
}, ExtArgs["result"]["episodeWatch"]>

export type EpisodeWatchSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  tmdbId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  watchedAt?: boolean
}, ExtArgs["result"]["episodeWatch"]>

export type EpisodeWatchSelectScalar = {
  id?: boolean
  username?: boolean
  tmdbId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  watchedAt?: boolean
}

export type EpisodeWatchOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "username" | "tmdbId" | "seasonNumber" | "episodeNumber" | "watchedAt", ExtArgs["result"]["episodeWatch"]>

export type $EpisodeWatchPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EpisodeWatch"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    username: string
    tmdbId: number
    seasonNumber: number
    episodeNumber: number
    watchedAt: Date
  }, ExtArgs["result"]["episodeWatch"]>
  composites: {}
}

export type EpisodeWatchGetPayload<S extends boolean | null | undefined | EpisodeWatchDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload, S>

export type EpisodeWatchCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EpisodeWatchFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EpisodeWatchCountAggregateInputType | true
  }

export interface EpisodeWatchDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EpisodeWatch'], meta: { name: 'EpisodeWatch' } }
  /**
   * Find zero or one EpisodeWatch that matches the filter.
   * @param {EpisodeWatchFindUniqueArgs} args - Arguments to find a EpisodeWatch
   * @example
   * // Get one EpisodeWatch
   * const episodeWatch = await prisma.episodeWatch.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EpisodeWatchFindUniqueArgs>(args: Prisma.SelectSubset<T, EpisodeWatchFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EpisodeWatch that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EpisodeWatchFindUniqueOrThrowArgs} args - Arguments to find a EpisodeWatch
   * @example
   * // Get one EpisodeWatch
   * const episodeWatch = await prisma.episodeWatch.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EpisodeWatchFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EpisodeWatchFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EpisodeWatch that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EpisodeWatchFindFirstArgs} args - Arguments to find a EpisodeWatch
   * @example
   * // Get one EpisodeWatch
   * const episodeWatch = await prisma.episodeWatch.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EpisodeWatchFindFirstArgs>(args?: Prisma.SelectSubset<T, EpisodeWatchFindFirstArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EpisodeWatch that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EpisodeWatchFindFirstOrThrowArgs} args - Arguments to find a EpisodeWatch
   * @example
   * // Get one EpisodeWatch
   * const episodeWatch = await prisma.episodeWatch.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EpisodeWatchFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EpisodeWatchFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EpisodeWatches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EpisodeWatchFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EpisodeWatches
   * const episodeWatches = await prisma.episodeWatch.findMany()
   * 
   * // Get first 10 EpisodeWatches
   * const episodeWatches = await prisma.episodeWatch.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const episodeWatchWithIdOnly = await prisma.episodeWatch.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EpisodeWatchFindManyArgs>(args?: Prisma.SelectSubset<T, EpisodeWatchFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EpisodeWatch.
   * @param {EpisodeWatchCreateArgs} args - Arguments to create a EpisodeWatch.
   * @example
   * // Create one EpisodeWatch
   * const EpisodeWatch = await prisma.episodeWatch.create({
   *   data: {
   *     // ... data to create a EpisodeWatch
   *   }
   * })
   * 
   */
  create<T extends EpisodeWatchCreateArgs>(args: Prisma.SelectSubset<T, EpisodeWatchCreateArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EpisodeWatches.
   * @param {EpisodeWatchCreateManyArgs} args - Arguments to create many EpisodeWatches.
   * @example
   * // Create many EpisodeWatches
   * const episodeWatch = await prisma.episodeWatch.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EpisodeWatchCreateManyArgs>(args?: Prisma.SelectSubset<T, EpisodeWatchCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EpisodeWatches and returns the data saved in the database.
   * @param {EpisodeWatchCreateManyAndReturnArgs} args - Arguments to create many EpisodeWatches.
   * @example
   * // Create many EpisodeWatches
   * const episodeWatch = await prisma.episodeWatch.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EpisodeWatches and only return the `id`
   * const episodeWatchWithIdOnly = await prisma.episodeWatch.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EpisodeWatchCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EpisodeWatchCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EpisodeWatch.
   * @param {EpisodeWatchDeleteArgs} args - Arguments to delete one EpisodeWatch.
   * @example
   * // Delete one EpisodeWatch
   * const EpisodeWatch = await prisma.episodeWatch.delete({
   *   where: {
   *     // ... filter to delete one EpisodeWatch
   *   }
   * })
   * 
   */
  delete<T extends EpisodeWatchDeleteArgs>(args: Prisma.SelectSubset<T, EpisodeWatchDeleteArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EpisodeWatch.
   * @param {EpisodeWatchUpdateArgs} args - Arguments to update one EpisodeWatch.
   * @example
   * // Update one EpisodeWatch
   * const episodeWatch = await prisma.episodeWatch.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EpisodeWatchUpdateArgs>(args: Prisma.SelectSubset<T, EpisodeWatchUpdateArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EpisodeWatches.
   * @param {EpisodeWatchDeleteManyArgs} args - Arguments to filter EpisodeWatches to delete.
   * @example
   * // Delete a few EpisodeWatches
   * const { count } = await prisma.episodeWatch.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EpisodeWatchDeleteManyArgs>(args?: Prisma.SelectSubset<T, EpisodeWatchDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EpisodeWatches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EpisodeWatchUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EpisodeWatches
   * const episodeWatch = await prisma.episodeWatch.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EpisodeWatchUpdateManyArgs>(args: Prisma.SelectSubset<T, EpisodeWatchUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EpisodeWatches and returns the data updated in the database.
   * @param {EpisodeWatchUpdateManyAndReturnArgs} args - Arguments to update many EpisodeWatches.
   * @example
   * // Update many EpisodeWatches
   * const episodeWatch = await prisma.episodeWatch.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EpisodeWatches and only return the `id`
   * const episodeWatchWithIdOnly = await prisma.episodeWatch.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EpisodeWatchUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EpisodeWatchUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EpisodeWatch.
   * @param {EpisodeWatchUpsertArgs} args - Arguments to update or create a EpisodeWatch.
   * @example
   * // Update or create a EpisodeWatch
   * const episodeWatch = await prisma.episodeWatch.upsert({
   *   create: {
   *     // ... data to create a EpisodeWatch
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EpisodeWatch we want to update
   *   }
   * })
   */
  upsert<T extends EpisodeWatchUpsertArgs>(args: Prisma.SelectSubset<T, EpisodeWatchUpsertArgs<ExtArgs>>): Prisma.Prisma__EpisodeWatchClient<runtime.Types.Result.GetResult<Prisma.$EpisodeWatchPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EpisodeWatches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EpisodeWatchCountArgs} args - Arguments to filter EpisodeWatches to count.
   * @example
   * // Count the number of EpisodeWatches
   * const count = await prisma.episodeWatch.count({
   *   where: {
   *     // ... the filter for the EpisodeWatches we want to count
   *   }
   * })
  **/
  count<T extends EpisodeWatchCountArgs>(
    args?: Prisma.Subset<T, EpisodeWatchCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EpisodeWatchCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EpisodeWatch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EpisodeWatchAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EpisodeWatchAggregateArgs>(args: Prisma.Subset<T, EpisodeWatchAggregateArgs>): Prisma.PrismaPromise<GetEpisodeWatchAggregateType<T>>

  /**
   * Group by EpisodeWatch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EpisodeWatchGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EpisodeWatchGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EpisodeWatchGroupByArgs['orderBy'] }
      : { orderBy?: EpisodeWatchGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EpisodeWatchGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEpisodeWatchGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EpisodeWatch model
 */
readonly fields: EpisodeWatchFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EpisodeWatch.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EpisodeWatchClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EpisodeWatch model
 */
export interface EpisodeWatchFieldRefs {
  readonly id: Prisma.FieldRef<"EpisodeWatch", 'String'>
  readonly username: Prisma.FieldRef<"EpisodeWatch", 'String'>
  readonly tmdbId: Prisma.FieldRef<"EpisodeWatch", 'Int'>
  readonly seasonNumber: Prisma.FieldRef<"EpisodeWatch", 'Int'>
  readonly episodeNumber: Prisma.FieldRef<"EpisodeWatch", 'Int'>
  readonly watchedAt: Prisma.FieldRef<"EpisodeWatch", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EpisodeWatch findUnique
 */
export type EpisodeWatchFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * Filter, which EpisodeWatch to fetch.
   */
  where: Prisma.EpisodeWatchWhereUniqueInput
}

/**
 * EpisodeWatch findUniqueOrThrow
 */
export type EpisodeWatchFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * Filter, which EpisodeWatch to fetch.
   */
  where: Prisma.EpisodeWatchWhereUniqueInput
}

/**
 * EpisodeWatch findFirst
 */
export type EpisodeWatchFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * Filter, which EpisodeWatch to fetch.
   */
  where?: Prisma.EpisodeWatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EpisodeWatches to fetch.
   */
  orderBy?: Prisma.EpisodeWatchOrderByWithRelationInput | Prisma.EpisodeWatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EpisodeWatches.
   */
  cursor?: Prisma.EpisodeWatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EpisodeWatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EpisodeWatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EpisodeWatches.
   */
  distinct?: Prisma.EpisodeWatchScalarFieldEnum | Prisma.EpisodeWatchScalarFieldEnum[]
}

/**
 * EpisodeWatch findFirstOrThrow
 */
export type EpisodeWatchFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * Filter, which EpisodeWatch to fetch.
   */
  where?: Prisma.EpisodeWatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EpisodeWatches to fetch.
   */
  orderBy?: Prisma.EpisodeWatchOrderByWithRelationInput | Prisma.EpisodeWatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EpisodeWatches.
   */
  cursor?: Prisma.EpisodeWatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EpisodeWatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EpisodeWatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EpisodeWatches.
   */
  distinct?: Prisma.EpisodeWatchScalarFieldEnum | Prisma.EpisodeWatchScalarFieldEnum[]
}

/**
 * EpisodeWatch findMany
 */
export type EpisodeWatchFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * Filter, which EpisodeWatches to fetch.
   */
  where?: Prisma.EpisodeWatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EpisodeWatches to fetch.
   */
  orderBy?: Prisma.EpisodeWatchOrderByWithRelationInput | Prisma.EpisodeWatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EpisodeWatches.
   */
  cursor?: Prisma.EpisodeWatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EpisodeWatches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EpisodeWatches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EpisodeWatches.
   */
  distinct?: Prisma.EpisodeWatchScalarFieldEnum | Prisma.EpisodeWatchScalarFieldEnum[]
}

/**
 * EpisodeWatch create
 */
export type EpisodeWatchCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * The data needed to create a EpisodeWatch.
   */
  data: Prisma.XOR<Prisma.EpisodeWatchCreateInput, Prisma.EpisodeWatchUncheckedCreateInput>
}

/**
 * EpisodeWatch createMany
 */
export type EpisodeWatchCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EpisodeWatches.
   */
  data: Prisma.EpisodeWatchCreateManyInput | Prisma.EpisodeWatchCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EpisodeWatch createManyAndReturn
 */
export type EpisodeWatchCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * The data used to create many EpisodeWatches.
   */
  data: Prisma.EpisodeWatchCreateManyInput | Prisma.EpisodeWatchCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EpisodeWatch update
 */
export type EpisodeWatchUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * The data needed to update a EpisodeWatch.
   */
  data: Prisma.XOR<Prisma.EpisodeWatchUpdateInput, Prisma.EpisodeWatchUncheckedUpdateInput>
  /**
   * Choose, which EpisodeWatch to update.
   */
  where: Prisma.EpisodeWatchWhereUniqueInput
}

/**
 * EpisodeWatch updateMany
 */
export type EpisodeWatchUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EpisodeWatches.
   */
  data: Prisma.XOR<Prisma.EpisodeWatchUpdateManyMutationInput, Prisma.EpisodeWatchUncheckedUpdateManyInput>
  /**
   * Filter which EpisodeWatches to update
   */
  where?: Prisma.EpisodeWatchWhereInput
  /**
   * Limit how many EpisodeWatches to update.
   */
  limit?: number
}

/**
 * EpisodeWatch updateManyAndReturn
 */
export type EpisodeWatchUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * The data used to update EpisodeWatches.
   */
  data: Prisma.XOR<Prisma.EpisodeWatchUpdateManyMutationInput, Prisma.EpisodeWatchUncheckedUpdateManyInput>
  /**
   * Filter which EpisodeWatches to update
   */
  where?: Prisma.EpisodeWatchWhereInput
  /**
   * Limit how many EpisodeWatches to update.
   */
  limit?: number
}

/**
 * EpisodeWatch upsert
 */
export type EpisodeWatchUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * The filter to search for the EpisodeWatch to update in case it exists.
   */
  where: Prisma.EpisodeWatchWhereUniqueInput
  /**
   * In case the EpisodeWatch found by the `where` argument doesn't exist, create a new EpisodeWatch with this data.
   */
  create: Prisma.XOR<Prisma.EpisodeWatchCreateInput, Prisma.EpisodeWatchUncheckedCreateInput>
  /**
   * In case the EpisodeWatch was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EpisodeWatchUpdateInput, Prisma.EpisodeWatchUncheckedUpdateInput>
}

/**
 * EpisodeWatch delete
 */
export type EpisodeWatchDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
  /**
   * Filter which EpisodeWatch to delete.
   */
  where: Prisma.EpisodeWatchWhereUniqueInput
}

/**
 * EpisodeWatch deleteMany
 */
export type EpisodeWatchDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EpisodeWatches to delete
   */
  where?: Prisma.EpisodeWatchWhereInput
  /**
   * Limit how many EpisodeWatches to delete.
   */
  limit?: number
}

/**
 * EpisodeWatch without action
 */
export type EpisodeWatchDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EpisodeWatch
   */
  select?: Prisma.EpisodeWatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EpisodeWatch
   */
  omit?: Prisma.EpisodeWatchOmit<ExtArgs> | null
}
