
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MediaTracking` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MediaTracking
 * 
 */
export type MediaTrackingModel = runtime.Types.Result.DefaultSelection<Prisma.$MediaTrackingPayload>

export type AggregateMediaTracking = {
  _count: MediaTrackingCountAggregateOutputType | null
  _avg: MediaTrackingAvgAggregateOutputType | null
  _sum: MediaTrackingSumAggregateOutputType | null
  _min: MediaTrackingMinAggregateOutputType | null
  _max: MediaTrackingMaxAggregateOutputType | null
}

export type MediaTrackingAvgAggregateOutputType = {
  tmdbId: number | null
  anilistId: number | null
  rating: number | null
  progress: number | null
}

export type MediaTrackingSumAggregateOutputType = {
  tmdbId: number | null
  anilistId: number | null
  rating: number | null
  progress: number | null
}

export type MediaTrackingMinAggregateOutputType = {
  id: string | null
  userId: string | null
  tmdbId: number | null
  anilistId: number | null
  mediaType: string | null
  status: string | null
  rating: number | null
  progress: number | null
  updatedAt: Date | null
}

export type MediaTrackingMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  tmdbId: number | null
  anilistId: number | null
  mediaType: string | null
  status: string | null
  rating: number | null
  progress: number | null
  updatedAt: Date | null
}

export type MediaTrackingCountAggregateOutputType = {
  id: number
  userId: number
  tmdbId: number
  anilistId: number
  mediaType: number
  status: number
  rating: number
  progress: number
  updatedAt: number
  _all: number
}


export type MediaTrackingAvgAggregateInputType = {
  tmdbId?: true
  anilistId?: true
  rating?: true
  progress?: true
}

export type MediaTrackingSumAggregateInputType = {
  tmdbId?: true
  anilistId?: true
  rating?: true
  progress?: true
}

export type MediaTrackingMinAggregateInputType = {
  id?: true
  userId?: true
  tmdbId?: true
  anilistId?: true
  mediaType?: true
  status?: true
  rating?: true
  progress?: true
  updatedAt?: true
}

export type MediaTrackingMaxAggregateInputType = {
  id?: true
  userId?: true
  tmdbId?: true
  anilistId?: true
  mediaType?: true
  status?: true
  rating?: true
  progress?: true
  updatedAt?: true
}

export type MediaTrackingCountAggregateInputType = {
  id?: true
  userId?: true
  tmdbId?: true
  anilistId?: true
  mediaType?: true
  status?: true
  rating?: true
  progress?: true
  updatedAt?: true
  _all?: true
}

export type MediaTrackingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MediaTracking to aggregate.
   */
  where?: Prisma.MediaTrackingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MediaTrackings to fetch.
   */
  orderBy?: Prisma.MediaTrackingOrderByWithRelationInput | Prisma.MediaTrackingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MediaTrackingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MediaTrackings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MediaTrackings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MediaTrackings
  **/
  _count?: true | MediaTrackingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MediaTrackingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MediaTrackingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MediaTrackingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MediaTrackingMaxAggregateInputType
}

export type GetMediaTrackingAggregateType<T extends MediaTrackingAggregateArgs> = {
      [P in keyof T & keyof AggregateMediaTracking]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMediaTracking[P]>
    : Prisma.GetScalarType<T[P], AggregateMediaTracking[P]>
}




export type MediaTrackingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MediaTrackingWhereInput
  orderBy?: Prisma.MediaTrackingOrderByWithAggregationInput | Prisma.MediaTrackingOrderByWithAggregationInput[]
  by: Prisma.MediaTrackingScalarFieldEnum[] | Prisma.MediaTrackingScalarFieldEnum
  having?: Prisma.MediaTrackingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MediaTrackingCountAggregateInputType | true
  _avg?: MediaTrackingAvgAggregateInputType
  _sum?: MediaTrackingSumAggregateInputType
  _min?: MediaTrackingMinAggregateInputType
  _max?: MediaTrackingMaxAggregateInputType
}

export type MediaTrackingGroupByOutputType = {
  id: string
  userId: string
  tmdbId: number
  anilistId: number | null
  mediaType: string
  status: string
  rating: number | null
  progress: number | null
  updatedAt: Date
  _count: MediaTrackingCountAggregateOutputType | null
  _avg: MediaTrackingAvgAggregateOutputType | null
  _sum: MediaTrackingSumAggregateOutputType | null
  _min: MediaTrackingMinAggregateOutputType | null
  _max: MediaTrackingMaxAggregateOutputType | null
}

export type GetMediaTrackingGroupByPayload<T extends MediaTrackingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MediaTrackingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MediaTrackingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MediaTrackingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MediaTrackingGroupByOutputType[P]>
      }
    >
  >



export type MediaTrackingWhereInput = {
  AND?: Prisma.MediaTrackingWhereInput | Prisma.MediaTrackingWhereInput[]
  OR?: Prisma.MediaTrackingWhereInput[]
  NOT?: Prisma.MediaTrackingWhereInput | Prisma.MediaTrackingWhereInput[]
  id?: Prisma.StringFilter<"MediaTracking"> | string
  userId?: Prisma.StringFilter<"MediaTracking"> | string
  tmdbId?: Prisma.IntFilter<"MediaTracking"> | number
  anilistId?: Prisma.IntNullableFilter<"MediaTracking"> | number | null
  mediaType?: Prisma.StringFilter<"MediaTracking"> | string
  status?: Prisma.StringFilter<"MediaTracking"> | string
  rating?: Prisma.FloatNullableFilter<"MediaTracking"> | number | null
  progress?: Prisma.IntNullableFilter<"MediaTracking"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"MediaTracking"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type MediaTrackingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  anilistId?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type MediaTrackingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_tmdbId_mediaType?: Prisma.MediaTrackingUserIdTmdbIdMediaTypeCompoundUniqueInput
  AND?: Prisma.MediaTrackingWhereInput | Prisma.MediaTrackingWhereInput[]
  OR?: Prisma.MediaTrackingWhereInput[]
  NOT?: Prisma.MediaTrackingWhereInput | Prisma.MediaTrackingWhereInput[]
  userId?: Prisma.StringFilter<"MediaTracking"> | string
  tmdbId?: Prisma.IntFilter<"MediaTracking"> | number
  anilistId?: Prisma.IntNullableFilter<"MediaTracking"> | number | null
  mediaType?: Prisma.StringFilter<"MediaTracking"> | string
  status?: Prisma.StringFilter<"MediaTracking"> | string
  rating?: Prisma.FloatNullableFilter<"MediaTracking"> | number | null
  progress?: Prisma.IntNullableFilter<"MediaTracking"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"MediaTracking"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_tmdbId_mediaType">

export type MediaTrackingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  anilistId?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MediaTrackingCountOrderByAggregateInput
  _avg?: Prisma.MediaTrackingAvgOrderByAggregateInput
  _max?: Prisma.MediaTrackingMaxOrderByAggregateInput
  _min?: Prisma.MediaTrackingMinOrderByAggregateInput
  _sum?: Prisma.MediaTrackingSumOrderByAggregateInput
}

export type MediaTrackingScalarWhereWithAggregatesInput = {
  AND?: Prisma.MediaTrackingScalarWhereWithAggregatesInput | Prisma.MediaTrackingScalarWhereWithAggregatesInput[]
  OR?: Prisma.MediaTrackingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MediaTrackingScalarWhereWithAggregatesInput | Prisma.MediaTrackingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MediaTracking"> | string
  userId?: Prisma.StringWithAggregatesFilter<"MediaTracking"> | string
  tmdbId?: Prisma.IntWithAggregatesFilter<"MediaTracking"> | number
  anilistId?: Prisma.IntNullableWithAggregatesFilter<"MediaTracking"> | number | null
  mediaType?: Prisma.StringWithAggregatesFilter<"MediaTracking"> | string
  status?: Prisma.StringWithAggregatesFilter<"MediaTracking"> | string
  rating?: Prisma.FloatNullableWithAggregatesFilter<"MediaTracking"> | number | null
  progress?: Prisma.IntNullableWithAggregatesFilter<"MediaTracking"> | number | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MediaTracking"> | Date | string
}

export type MediaTrackingCreateInput = {
  id?: string
  tmdbId: number
  anilistId?: number | null
  mediaType: string
  status: string
  rating?: number | null
  progress?: number | null
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTrackingsInput
}

export type MediaTrackingUncheckedCreateInput = {
  id?: string
  userId: string
  tmdbId: number
  anilistId?: number | null
  mediaType: string
  status: string
  rating?: number | null
  progress?: number | null
  updatedAt?: Date | string
}

export type MediaTrackingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  anilistId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  progress?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTrackingsNestedInput
}

export type MediaTrackingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  anilistId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  progress?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MediaTrackingCreateManyInput = {
  id?: string
  userId: string
  tmdbId: number
  anilistId?: number | null
  mediaType: string
  status: string
  rating?: number | null
  progress?: number | null
  updatedAt?: Date | string
}

export type MediaTrackingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  anilistId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  progress?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MediaTrackingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  anilistId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  progress?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MediaTrackingListRelationFilter = {
  every?: Prisma.MediaTrackingWhereInput
  some?: Prisma.MediaTrackingWhereInput
  none?: Prisma.MediaTrackingWhereInput
}

export type MediaTrackingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MediaTrackingUserIdTmdbIdMediaTypeCompoundUniqueInput = {
  userId: string
  tmdbId: number
  mediaType: string
}

export type MediaTrackingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  anilistId?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MediaTrackingAvgOrderByAggregateInput = {
  tmdbId?: Prisma.SortOrder
  anilistId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  progress?: Prisma.SortOrder
}

export type MediaTrackingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  anilistId?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MediaTrackingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  anilistId?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MediaTrackingSumOrderByAggregateInput = {
  tmdbId?: Prisma.SortOrder
  anilistId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  progress?: Prisma.SortOrder
}

export type MediaTrackingCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MediaTrackingCreateWithoutUserInput, Prisma.MediaTrackingUncheckedCreateWithoutUserInput> | Prisma.MediaTrackingCreateWithoutUserInput[] | Prisma.MediaTrackingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MediaTrackingCreateOrConnectWithoutUserInput | Prisma.MediaTrackingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MediaTrackingCreateManyUserInputEnvelope
  connect?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
}

export type MediaTrackingUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MediaTrackingCreateWithoutUserInput, Prisma.MediaTrackingUncheckedCreateWithoutUserInput> | Prisma.MediaTrackingCreateWithoutUserInput[] | Prisma.MediaTrackingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MediaTrackingCreateOrConnectWithoutUserInput | Prisma.MediaTrackingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MediaTrackingCreateManyUserInputEnvelope
  connect?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
}

export type MediaTrackingUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MediaTrackingCreateWithoutUserInput, Prisma.MediaTrackingUncheckedCreateWithoutUserInput> | Prisma.MediaTrackingCreateWithoutUserInput[] | Prisma.MediaTrackingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MediaTrackingCreateOrConnectWithoutUserInput | Prisma.MediaTrackingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MediaTrackingUpsertWithWhereUniqueWithoutUserInput | Prisma.MediaTrackingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MediaTrackingCreateManyUserInputEnvelope
  set?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  disconnect?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  delete?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  connect?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  update?: Prisma.MediaTrackingUpdateWithWhereUniqueWithoutUserInput | Prisma.MediaTrackingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MediaTrackingUpdateManyWithWhereWithoutUserInput | Prisma.MediaTrackingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MediaTrackingScalarWhereInput | Prisma.MediaTrackingScalarWhereInput[]
}

export type MediaTrackingUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MediaTrackingCreateWithoutUserInput, Prisma.MediaTrackingUncheckedCreateWithoutUserInput> | Prisma.MediaTrackingCreateWithoutUserInput[] | Prisma.MediaTrackingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MediaTrackingCreateOrConnectWithoutUserInput | Prisma.MediaTrackingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MediaTrackingUpsertWithWhereUniqueWithoutUserInput | Prisma.MediaTrackingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MediaTrackingCreateManyUserInputEnvelope
  set?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  disconnect?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  delete?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  connect?: Prisma.MediaTrackingWhereUniqueInput | Prisma.MediaTrackingWhereUniqueInput[]
  update?: Prisma.MediaTrackingUpdateWithWhereUniqueWithoutUserInput | Prisma.MediaTrackingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MediaTrackingUpdateManyWithWhereWithoutUserInput | Prisma.MediaTrackingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MediaTrackingScalarWhereInput | Prisma.MediaTrackingScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type MediaTrackingCreateWithoutUserInput = {
  id?: string
  tmdbId: number
  anilistId?: number | null
  mediaType: string
  status: string
  rating?: number | null
  progress?: number | null
  updatedAt?: Date | string
}

export type MediaTrackingUncheckedCreateWithoutUserInput = {
  id?: string
  tmdbId: number
  anilistId?: number | null
  mediaType: string
  status: string
  rating?: number | null
  progress?: number | null
  updatedAt?: Date | string
}

export type MediaTrackingCreateOrConnectWithoutUserInput = {
  where: Prisma.MediaTrackingWhereUniqueInput
  create: Prisma.XOR<Prisma.MediaTrackingCreateWithoutUserInput, Prisma.MediaTrackingUncheckedCreateWithoutUserInput>
}

export type MediaTrackingCreateManyUserInputEnvelope = {
  data: Prisma.MediaTrackingCreateManyUserInput | Prisma.MediaTrackingCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type MediaTrackingUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.MediaTrackingWhereUniqueInput
  update: Prisma.XOR<Prisma.MediaTrackingUpdateWithoutUserInput, Prisma.MediaTrackingUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.MediaTrackingCreateWithoutUserInput, Prisma.MediaTrackingUncheckedCreateWithoutUserInput>
}

export type MediaTrackingUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.MediaTrackingWhereUniqueInput
  data: Prisma.XOR<Prisma.MediaTrackingUpdateWithoutUserInput, Prisma.MediaTrackingUncheckedUpdateWithoutUserInput>
}

export type MediaTrackingUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.MediaTrackingScalarWhereInput
  data: Prisma.XOR<Prisma.MediaTrackingUpdateManyMutationInput, Prisma.MediaTrackingUncheckedUpdateManyWithoutUserInput>
}

export type MediaTrackingScalarWhereInput = {
  AND?: Prisma.MediaTrackingScalarWhereInput | Prisma.MediaTrackingScalarWhereInput[]
  OR?: Prisma.MediaTrackingScalarWhereInput[]
  NOT?: Prisma.MediaTrackingScalarWhereInput | Prisma.MediaTrackingScalarWhereInput[]
  id?: Prisma.StringFilter<"MediaTracking"> | string
  userId?: Prisma.StringFilter<"MediaTracking"> | string
  tmdbId?: Prisma.IntFilter<"MediaTracking"> | number
  anilistId?: Prisma.IntNullableFilter<"MediaTracking"> | number | null
  mediaType?: Prisma.StringFilter<"MediaTracking"> | string
  status?: Prisma.StringFilter<"MediaTracking"> | string
  rating?: Prisma.FloatNullableFilter<"MediaTracking"> | number | null
  progress?: Prisma.IntNullableFilter<"MediaTracking"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"MediaTracking"> | Date | string
}

export type MediaTrackingCreateManyUserInput = {
  id?: string
  tmdbId: number
  anilistId?: number | null
  mediaType: string
  status: string
  rating?: number | null
  progress?: number | null
  updatedAt?: Date | string
}

export type MediaTrackingUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  anilistId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  progress?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MediaTrackingUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  anilistId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  progress?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MediaTrackingUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  anilistId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  progress?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MediaTrackingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  anilistId?: boolean
  mediaType?: boolean
  status?: boolean
  rating?: boolean
  progress?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mediaTracking"]>

export type MediaTrackingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  anilistId?: boolean
  mediaType?: boolean
  status?: boolean
  rating?: boolean
  progress?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mediaTracking"]>

export type MediaTrackingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  anilistId?: boolean
  mediaType?: boolean
  status?: boolean
  rating?: boolean
  progress?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mediaTracking"]>

export type MediaTrackingSelectScalar = {
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  anilistId?: boolean
  mediaType?: boolean
  status?: boolean
  rating?: boolean
  progress?: boolean
  updatedAt?: boolean
}

export type MediaTrackingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "tmdbId" | "anilistId" | "mediaType" | "status" | "rating" | "progress" | "updatedAt", ExtArgs["result"]["mediaTracking"]>
export type MediaTrackingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MediaTrackingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MediaTrackingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $MediaTrackingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MediaTracking"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    tmdbId: number
    anilistId: number | null
    mediaType: string
    status: string
    rating: number | null
    progress: number | null
    updatedAt: Date
  }, ExtArgs["result"]["mediaTracking"]>
  composites: {}
}

export type MediaTrackingGetPayload<S extends boolean | null | undefined | MediaTrackingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload, S>

export type MediaTrackingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MediaTrackingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MediaTrackingCountAggregateInputType | true
  }

export interface MediaTrackingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MediaTracking'], meta: { name: 'MediaTracking' } }
  /**
   * Find zero or one MediaTracking that matches the filter.
   * @param {MediaTrackingFindUniqueArgs} args - Arguments to find a MediaTracking
   * @example
   * // Get one MediaTracking
   * const mediaTracking = await prisma.mediaTracking.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MediaTrackingFindUniqueArgs>(args: Prisma.SelectSubset<T, MediaTrackingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MediaTracking that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MediaTrackingFindUniqueOrThrowArgs} args - Arguments to find a MediaTracking
   * @example
   * // Get one MediaTracking
   * const mediaTracking = await prisma.mediaTracking.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MediaTrackingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MediaTrackingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MediaTracking that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MediaTrackingFindFirstArgs} args - Arguments to find a MediaTracking
   * @example
   * // Get one MediaTracking
   * const mediaTracking = await prisma.mediaTracking.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MediaTrackingFindFirstArgs>(args?: Prisma.SelectSubset<T, MediaTrackingFindFirstArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MediaTracking that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MediaTrackingFindFirstOrThrowArgs} args - Arguments to find a MediaTracking
   * @example
   * // Get one MediaTracking
   * const mediaTracking = await prisma.mediaTracking.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MediaTrackingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MediaTrackingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MediaTrackings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MediaTrackingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MediaTrackings
   * const mediaTrackings = await prisma.mediaTracking.findMany()
   * 
   * // Get first 10 MediaTrackings
   * const mediaTrackings = await prisma.mediaTracking.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mediaTrackingWithIdOnly = await prisma.mediaTracking.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MediaTrackingFindManyArgs>(args?: Prisma.SelectSubset<T, MediaTrackingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MediaTracking.
   * @param {MediaTrackingCreateArgs} args - Arguments to create a MediaTracking.
   * @example
   * // Create one MediaTracking
   * const MediaTracking = await prisma.mediaTracking.create({
   *   data: {
   *     // ... data to create a MediaTracking
   *   }
   * })
   * 
   */
  create<T extends MediaTrackingCreateArgs>(args: Prisma.SelectSubset<T, MediaTrackingCreateArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MediaTrackings.
   * @param {MediaTrackingCreateManyArgs} args - Arguments to create many MediaTrackings.
   * @example
   * // Create many MediaTrackings
   * const mediaTracking = await prisma.mediaTracking.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MediaTrackingCreateManyArgs>(args?: Prisma.SelectSubset<T, MediaTrackingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MediaTrackings and returns the data saved in the database.
   * @param {MediaTrackingCreateManyAndReturnArgs} args - Arguments to create many MediaTrackings.
   * @example
   * // Create many MediaTrackings
   * const mediaTracking = await prisma.mediaTracking.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MediaTrackings and only return the `id`
   * const mediaTrackingWithIdOnly = await prisma.mediaTracking.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MediaTrackingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MediaTrackingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MediaTracking.
   * @param {MediaTrackingDeleteArgs} args - Arguments to delete one MediaTracking.
   * @example
   * // Delete one MediaTracking
   * const MediaTracking = await prisma.mediaTracking.delete({
   *   where: {
   *     // ... filter to delete one MediaTracking
   *   }
   * })
   * 
   */
  delete<T extends MediaTrackingDeleteArgs>(args: Prisma.SelectSubset<T, MediaTrackingDeleteArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MediaTracking.
   * @param {MediaTrackingUpdateArgs} args - Arguments to update one MediaTracking.
   * @example
   * // Update one MediaTracking
   * const mediaTracking = await prisma.mediaTracking.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MediaTrackingUpdateArgs>(args: Prisma.SelectSubset<T, MediaTrackingUpdateArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MediaTrackings.
   * @param {MediaTrackingDeleteManyArgs} args - Arguments to filter MediaTrackings to delete.
   * @example
   * // Delete a few MediaTrackings
   * const { count } = await prisma.mediaTracking.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MediaTrackingDeleteManyArgs>(args?: Prisma.SelectSubset<T, MediaTrackingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MediaTrackings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MediaTrackingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MediaTrackings
   * const mediaTracking = await prisma.mediaTracking.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MediaTrackingUpdateManyArgs>(args: Prisma.SelectSubset<T, MediaTrackingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MediaTrackings and returns the data updated in the database.
   * @param {MediaTrackingUpdateManyAndReturnArgs} args - Arguments to update many MediaTrackings.
   * @example
   * // Update many MediaTrackings
   * const mediaTracking = await prisma.mediaTracking.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MediaTrackings and only return the `id`
   * const mediaTrackingWithIdOnly = await prisma.mediaTracking.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MediaTrackingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MediaTrackingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MediaTracking.
   * @param {MediaTrackingUpsertArgs} args - Arguments to update or create a MediaTracking.
   * @example
   * // Update or create a MediaTracking
   * const mediaTracking = await prisma.mediaTracking.upsert({
   *   create: {
   *     // ... data to create a MediaTracking
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MediaTracking we want to update
   *   }
   * })
   */
  upsert<T extends MediaTrackingUpsertArgs>(args: Prisma.SelectSubset<T, MediaTrackingUpsertArgs<ExtArgs>>): Prisma.Prisma__MediaTrackingClient<runtime.Types.Result.GetResult<Prisma.$MediaTrackingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MediaTrackings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MediaTrackingCountArgs} args - Arguments to filter MediaTrackings to count.
   * @example
   * // Count the number of MediaTrackings
   * const count = await prisma.mediaTracking.count({
   *   where: {
   *     // ... the filter for the MediaTrackings we want to count
   *   }
   * })
  **/
  count<T extends MediaTrackingCountArgs>(
    args?: Prisma.Subset<T, MediaTrackingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MediaTrackingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MediaTracking.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MediaTrackingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MediaTrackingAggregateArgs>(args: Prisma.Subset<T, MediaTrackingAggregateArgs>): Prisma.PrismaPromise<GetMediaTrackingAggregateType<T>>

  /**
   * Group by MediaTracking.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MediaTrackingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MediaTrackingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MediaTrackingGroupByArgs['orderBy'] }
      : { orderBy?: MediaTrackingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MediaTrackingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMediaTrackingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MediaTracking model
 */
readonly fields: MediaTrackingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MediaTracking.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MediaTrackingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MediaTracking model
 */
export interface MediaTrackingFieldRefs {
  readonly id: Prisma.FieldRef<"MediaTracking", 'String'>
  readonly userId: Prisma.FieldRef<"MediaTracking", 'String'>
  readonly tmdbId: Prisma.FieldRef<"MediaTracking", 'Int'>
  readonly anilistId: Prisma.FieldRef<"MediaTracking", 'Int'>
  readonly mediaType: Prisma.FieldRef<"MediaTracking", 'String'>
  readonly status: Prisma.FieldRef<"MediaTracking", 'String'>
  readonly rating: Prisma.FieldRef<"MediaTracking", 'Float'>
  readonly progress: Prisma.FieldRef<"MediaTracking", 'Int'>
  readonly updatedAt: Prisma.FieldRef<"MediaTracking", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MediaTracking findUnique
 */
export type MediaTrackingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * Filter, which MediaTracking to fetch.
   */
  where: Prisma.MediaTrackingWhereUniqueInput
}

/**
 * MediaTracking findUniqueOrThrow
 */
export type MediaTrackingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * Filter, which MediaTracking to fetch.
   */
  where: Prisma.MediaTrackingWhereUniqueInput
}

/**
 * MediaTracking findFirst
 */
export type MediaTrackingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * Filter, which MediaTracking to fetch.
   */
  where?: Prisma.MediaTrackingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MediaTrackings to fetch.
   */
  orderBy?: Prisma.MediaTrackingOrderByWithRelationInput | Prisma.MediaTrackingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MediaTrackings.
   */
  cursor?: Prisma.MediaTrackingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MediaTrackings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MediaTrackings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MediaTrackings.
   */
  distinct?: Prisma.MediaTrackingScalarFieldEnum | Prisma.MediaTrackingScalarFieldEnum[]
}

/**
 * MediaTracking findFirstOrThrow
 */
export type MediaTrackingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * Filter, which MediaTracking to fetch.
   */
  where?: Prisma.MediaTrackingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MediaTrackings to fetch.
   */
  orderBy?: Prisma.MediaTrackingOrderByWithRelationInput | Prisma.MediaTrackingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MediaTrackings.
   */
  cursor?: Prisma.MediaTrackingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MediaTrackings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MediaTrackings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MediaTrackings.
   */
  distinct?: Prisma.MediaTrackingScalarFieldEnum | Prisma.MediaTrackingScalarFieldEnum[]
}

/**
 * MediaTracking findMany
 */
export type MediaTrackingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * Filter, which MediaTrackings to fetch.
   */
  where?: Prisma.MediaTrackingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MediaTrackings to fetch.
   */
  orderBy?: Prisma.MediaTrackingOrderByWithRelationInput | Prisma.MediaTrackingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MediaTrackings.
   */
  cursor?: Prisma.MediaTrackingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MediaTrackings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MediaTrackings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MediaTrackings.
   */
  distinct?: Prisma.MediaTrackingScalarFieldEnum | Prisma.MediaTrackingScalarFieldEnum[]
}

/**
 * MediaTracking create
 */
export type MediaTrackingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * The data needed to create a MediaTracking.
   */
  data: Prisma.XOR<Prisma.MediaTrackingCreateInput, Prisma.MediaTrackingUncheckedCreateInput>
}

/**
 * MediaTracking createMany
 */
export type MediaTrackingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MediaTrackings.
   */
  data: Prisma.MediaTrackingCreateManyInput | Prisma.MediaTrackingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MediaTracking createManyAndReturn
 */
export type MediaTrackingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * The data used to create many MediaTrackings.
   */
  data: Prisma.MediaTrackingCreateManyInput | Prisma.MediaTrackingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MediaTracking update
 */
export type MediaTrackingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * The data needed to update a MediaTracking.
   */
  data: Prisma.XOR<Prisma.MediaTrackingUpdateInput, Prisma.MediaTrackingUncheckedUpdateInput>
  /**
   * Choose, which MediaTracking to update.
   */
  where: Prisma.MediaTrackingWhereUniqueInput
}

/**
 * MediaTracking updateMany
 */
export type MediaTrackingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MediaTrackings.
   */
  data: Prisma.XOR<Prisma.MediaTrackingUpdateManyMutationInput, Prisma.MediaTrackingUncheckedUpdateManyInput>
  /**
   * Filter which MediaTrackings to update
   */
  where?: Prisma.MediaTrackingWhereInput
  /**
   * Limit how many MediaTrackings to update.
   */
  limit?: number
}

/**
 * MediaTracking updateManyAndReturn
 */
export type MediaTrackingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * The data used to update MediaTrackings.
   */
  data: Prisma.XOR<Prisma.MediaTrackingUpdateManyMutationInput, Prisma.MediaTrackingUncheckedUpdateManyInput>
  /**
   * Filter which MediaTrackings to update
   */
  where?: Prisma.MediaTrackingWhereInput
  /**
   * Limit how many MediaTrackings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MediaTracking upsert
 */
export type MediaTrackingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * The filter to search for the MediaTracking to update in case it exists.
   */
  where: Prisma.MediaTrackingWhereUniqueInput
  /**
   * In case the MediaTracking found by the `where` argument doesn't exist, create a new MediaTracking with this data.
   */
  create: Prisma.XOR<Prisma.MediaTrackingCreateInput, Prisma.MediaTrackingUncheckedCreateInput>
  /**
   * In case the MediaTracking was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MediaTrackingUpdateInput, Prisma.MediaTrackingUncheckedUpdateInput>
}

/**
 * MediaTracking delete
 */
export type MediaTrackingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
  /**
   * Filter which MediaTracking to delete.
   */
  where: Prisma.MediaTrackingWhereUniqueInput
}

/**
 * MediaTracking deleteMany
 */
export type MediaTrackingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MediaTrackings to delete
   */
  where?: Prisma.MediaTrackingWhereInput
  /**
   * Limit how many MediaTrackings to delete.
   */
  limit?: number
}

/**
 * MediaTracking without action
 */
export type MediaTrackingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MediaTracking
   */
  select?: Prisma.MediaTrackingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MediaTracking
   */
  omit?: Prisma.MediaTrackingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaTrackingInclude<ExtArgs> | null
}
