-- Run this in Supabase SQL Editor to create search_logs table
CREATE TABLE IF NOT EXISTS search_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL,
  tmdb_id INTEGER,
  media_type TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_search_logs_query ON search_logs (query, created_at DESC);
