-- Phase 1: Data Layer Enhancement for Data Product
-- Run in Supabase SQL Editor

-- 1. Enhance search_logs
ALTER TABLE search_logs 
ADD COLUMN IF NOT EXISTS clicked_tmdb_id INTEGER,
ADD COLUMN IF NOT EXISTS country TEXT;

-- 2. Content visit tracking
CREATE TABLE IF NOT EXISTS content_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT NOT NULL,
  username TEXT,
  source TEXT DEFAULT 'direct',
  country TEXT,
  device TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_content_visits_tmdb ON content_visits(tmdb_id, media_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_visits_country ON content_visits(country, created_at DESC);

-- 3. Analytics schema
CREATE SCHEMA IF NOT EXISTS analytics;

-- Weekly content trends (aggregated from raw data)
CREATE TABLE IF NOT EXISTS analytics.weekly_content_trends (
  week_start DATE NOT NULL,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT NOT NULL,
  title TEXT,
  search_count INTEGER DEFAULT 0,
  visit_count INTEGER DEFAULT 0,
  tracking_adds INTEGER DEFAULT 0,
  tracking_completions INTEGER DEFAULT 0,
  avg_rating NUMERIC(3,2),
  review_count INTEGER DEFAULT 0,
  country TEXT DEFAULT 'all',
  PRIMARY KEY (week_start, tmdb_id, media_type, country)
);

-- Daily activity summary
CREATE TABLE IF NOT EXISTS analytics.daily_activity (
  date DATE PRIMARY KEY,
  total_searches INTEGER DEFAULT 0,
  total_visits INTEGER DEFAULT 0,
  total_tracking_changes INTEGER DEFAULT 0,
  total_reviews INTEGER DEFAULT 0,
  unique_users INTEGER DEFAULT 0
);

-- Enable RLS on content_visits (public can insert, admin can read)
ALTER TABLE content_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert" ON content_visits FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin read" ON content_visits FOR SELECT USING (
  EXISTS (SELECT 1 FROM users WHERE username = auth.uid()::text AND role = 'admin')
);
