
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model SearchLog
 * 
 */
export type SearchLog = Prisma.SearchLogModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model MediaTracking
 * 
 */
export type MediaTracking = Prisma.MediaTrackingModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model ReviewComment
 * 
 */
export type ReviewComment = Prisma.ReviewCommentModel
/**
 * Model Report
 * 
 */
export type Report = Prisma.ReportModel
/**
 * Model EpisodeWatch
 * 
 */
export type EpisodeWatch = Prisma.EpisodeWatchModel
/**
 * Model UserList
 * 
 */
export type UserList = Prisma.UserListModel
/**
 * Model ListItem
 * 
 */
export type ListItem = Prisma.ListItemModel
/**
 * Model Follow
 * 
 */
export type Follow = Prisma.FollowModel
